#!/bin/sh
#TODO mechanism to get random picture
case "$1" in
    lock)
        i3lock -i $(ls ~/lock_pictures/*.png | shuf -n1)
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        i3lock -i ~/lock_pictures/me1.png && systemctl suspend
        ;;
    hibernate)
        i3lock -i ~/lock_pictures/me1.png && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0

